### PR TITLE
Support for POP3 and IMAP

### PR DESCRIPTION
**Pull request by marcosdiez**
This PR adds `dovecot` to MailDev, which allows it to support POP3 and IMAP

fixes https://github.com/djfarrelly/MailDev/issues/166

One can try it here: https://hub.docker.com/r/marcosdiez/maildev/

### CODE REVIEW

**Comment by oktapodia** [comment]
Sorry it's been a long time ago, can you please resolve the conflicts?

**Comment by clrh** [comment]
I like the idea, I would be glad to see a come back of this pr (I unable to do it). I could test.

**Comment by marcosdiez** [comment]
Sorry, but I won't have time to do that. I am in a different project now.
That being said, my container that has both pop and imap still works: marcosdiez/maildev:latest 
that might solve your immediate problem.

**Comment by andreadelfante** [comment]
Hi, any news about this?

**Comment by djfarrelly** [comment]
This is out of the scope of the Maildev project right now. I think this might be better as a standalone package or container - I think this bloats what is already there, although I'm happy to publish a secondary package like `maildev-dovecot`. 

Thanks for this work, if someone wants to work on the above idea, please feel free to comment or propose the solution in a new issue.

**Pull request closed without merging**
