### PR TITLE
fix(420): maildev does not fail to start when using --auto-relay together with --mail-directory

### PR DESCRIPTION
**Pull request by jeandonaldroselin**
relative to issue #420

### CODE REVIEW

**Comment by jeandonaldroselin** [comment]
Cc @djfarrelly,

This is a blocking issue on the nice **mail-directory** option you added.
Please can you check this fix and make it available officially for any user ?
Thank you in advance.

**Comment by jeandonaldroselin** [comment]
Hello,

@MargaritaSav @rwaness @jerome-rdlv @dimbslmh

Please can you have a look at the following PR ?

I hope this repository is not just abandoned :o

**Comment by jeandonaldroselin** [comment]
Hello,

@MargaritaSav @rwaness @jerome-rdlv @dimbslmh @soulteary @jan--f

Please can you have a look at the following PR ?

I hope this repository is not just abandoned :o

**Comment by 3XC1T3D** [comment]
i don't think the contributors will merge the pull request :/ there is still a critical open cve , which was also not fixed by the contributors

**Comment by dimbslmh** [comment]
Sorry, I'm not part of the contributors so I can't help. 

A fork is mentioned here which includes the CVE fix https://github.com/maildev/maildev/issues/498 which may or may not end up in this repo.

There must be alternatives out there to try out. Google search: `smtp server development` or `smtp server development docker`

**Comment by 3XC1T3D** [comment]
@dimbslmh i searched a bit - a really alternative with the exact feature set like maildev doesnt exist 😅

**Comment by dimbslmh** [comment]
> @dimbslmh i searched a bit - a really alternative with the exact feature set like maildev doesnt exist 😅 

Are you sure? I found this after a few minutes: https://github.com/axllent/mailpit

**Comment by 3XC1T3D** [comment]
> > @dimbslmh i searched a bit - a really alternative with the exact feature set like maildev doesnt exist 😅 
> 
> Are you sure? I found this after a few minutes: https://github.com/axllent/mailpit and **is actively maintained**.
> 
> Edit: https://mailpit.axllent.org

thank you for the hint! 😍

**Comment by djfarrelly** [comment]
Merged - will be in the next 2.x release

**Pull request merged**
