### PR TITLE
spring boot configuration added

### PR DESCRIPTION
**Pull request by dipu11**
To use the SMTP server for the spring boot app, I have added the configuration for the `application.properties` file or `application.yml` file

### CODE REVIEW

**Comment by dancer1325** [comment]
Hi @dipu11 , do you have some demo project to check that it works? Because I would expect some error throw by the `javax.mail` or whatever SMTP interface you use, if you specify `starttls`, without passing `spring.mail.username` and `spring.mail.password`

**Comment by dipu11** [comment]
@dancer1325 , I have used this same configuration(without setting user/pass) in at least two production-grade projects for testing emails.
Unfortunately, I don't have such demo projects to link here.

**Comment by Frequency21** [comment]
@dipu11 Would you mind to create a demo project or take a glance at my configs or share some tips, please?

I am trying to setup a local spring (5.3.4) application to send emails to a local smtp server (maildev) but it fails to connect when I set MAILDEV_INCOMING_SECURE. (Without TLS related options it works perfectly)

Also I use mkcert which installs the rootCA to system and java truststore. So I am pretty sure that the self-signed cert is valid. (I can open the maildev site with https on chrome)

My configurations:
```env
MAILDEV_SMTP_PORT=587

MAILDEV_OUTGOING_HOST=192.168.100.73
MAILDEV_OUTGOING_PORT=465

MAILDEV_HTTPS=true
MAILDEV_OUTGOING_SECURE=true
MAILDEV_INCOMING_SECURE=true
MAILDEV_INCOMING_CERT=.\certs\maildev.pem
MAILDEV_INCOMING_KEY=.\certs\maildev-key.pem
MAILDEV_HTTPS_CERT=.\certs\maildev.pem
MAILDEV_HTTPS_KEY=.\certs\maildev-key.pem
MAILDEV_INCOMING_USER=test
MAILDEV_INCOMING_PASS=test

MAILDEV_IP=192.168.100.73
MAILDEV_WEB_IP=192.168.100.73

NODE_EXTRA_CA_CERTS=...\mkcert\rootCA.pem
```

Spring:
```yaml
spring:
  mail:
    host: 192.168.100.73
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          starttls.required: true
          timeout: 5000
          writetimeout: 5000
          connectiontimeout: 5000
    username: test
    password: test
    test-connection: true
```

**Comment by Frequency21** [comment]
I solved my issue by adding an extra configuration to spring. 

```yaml
spring:
  mail:
    properties:
      mail.smtp:
          socketFactory.class: javax.net.ssl.SSLSocketFactory
```

Not sure yet why it was needed.

**Pull request merged**
