### PR TITLE
docs: adjust document wording

### PR DESCRIPTION
**Pull request by bish0polis**
Like Traffic and Knowledge, the plural of Mail and Email is still Mail and Email.

### CODE REVIEW

**Comment by soulteary** [comment]
@LoneRifle @djfarrelly For this detail, which word do you think would be more appropriate?

**Review by LoneRifle — APPROVED** [review]
imo, the term "email" and "emails" can be used, depending on context. If referring to more than one email that is still a tractable number, "emails" should be used (as in `5 unread emails`). In this context, email can be used as a non-counting noun.

**Comment by bish0polis** [comment]
> imo

There are rules for that kind of word independent of opinion.  Don't confuse 'syntactically correct' with 'popular'.

**Comment by soulteary** [comment]
> I think this does read better than before, so along with @LoneRifle - I'm for this change :)

OK, then I'll merge this pr, and deal with conflicts. thanks @bish0polis @LoneRifle @djfarrelly

**Comment by soulteary** [comment]
Thanks for the contribution, the code has been merged, in the next version, we will add you as a contributor, looking forward to your more participation. @bish0polis 

https://github.com/maildev/maildev/pull/395

**Pull request closed without merging**
